# Generated by Django 4.2.4 on 2023-08-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255, verbose_name='用户名')),
                ('PassWord', models.CharField(max_length=20, verbose_name='密码')),
                ('PhoneNumber', models.IntegerField(max_length=11, verbose_name='电话号码')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
