# Generated by Django 4.2.4 on 2023-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255, verbose_name='用户名')),
                ('PassWord', models.CharField(max_length=15, verbose_name='密码')),
                ('PhoneNumber', models.IntegerField(verbose_name='电话号码')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('UserToken', models.CharField(default='', max_length=255, verbose_name='Token')),
            ],
        ),
    ]
