# Generated by Django 4.2.4 on 2023-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Token',
            field=models.CharField(default='', max_length=255, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='PassWord',
            field=models.CharField(max_length=15, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='PhoneNumber',
            field=models.IntegerField(verbose_name='电话号码'),
        ),
    ]
